Rename wasi_llm -> wasmedge_llmc
WasmEdge/wasmedge-llmc pull request #3
Opened 2024-09-04 07:51 UTC by junaire

Depends on https://github.com/WasmEdge/WasmEdge/pull/3731

2024-09-04 08:20 UTC, hydai requested changes

2024-09-04 08:20 UTC, hydai commented on wasmedge-llmc/src/llmc_interface.rs
> +    #[link(wasm_import_module = "wasmedge_llm")]
This should be `wasmedge_llmc`.

2024-09-04 08:40 UTC, junaire commented on wasmedge-llmc/src/llmc_interface.rs
> +    #[link(wasm_import_module = "wasmedge_llm")]
good catch, fixed

2024-09-05 19:29 UTC, hydai approved these changes

2024-09-10 04:37 UTC, hydai commented
Hi @junaire 
I just merged a PR to disable the WasmEdge AOT feature and remove the `lld` related dependencies to reduce the CI cost. Please fix the conflict in `build.yml`. Thanks.

2024-09-10 05:08 UTC, junaire commented
> Hi @junaire I just merged a PR to disable the WasmEdge AOT feature and remove the `lld` related dependencies to reduce the CI cost. Please fix the conflict in `build.yml`. Thanks.

done

2024-09-10 05:16 UTC, merged